#!/bin/bash
##################################################################################################################
#tput setaf 0 = black
#tput setaf 1 = red
#tput setaf 2 = green
#tput setaf 3 = yellow
#tput setaf 4 = dark blue
#tput setaf 5 = purple
#tput setaf 6 = cyan
#tput setaf 7 = gray
#tput setaf 8 = light blue
##################################################################################################################

tput setaf 3;
echo ""
echo "################################################################"
echo "Install Stardict-oald files from source"
echo "################################################################"
echo ""
echo;tput sgr0

# Install Stardict
sudo apt install stardict -y

sudo mkdir -p "/usr/share/stardict/dic/oald"
cd oald-files/
sudo install -m 644 *.dict.dz *.idx *.ifo /usr/share/stardict/dic/oald/

tput setaf 2;
echo ""
echo "################################################################"
echo "Stardict-oald Packages has been installed"
echo "################################################################"
echo ""
echo;tput sgr0

