#!/bin/bash
##################################################################################################################
#tput setaf 0 = black
#tput setaf 1 = red
#tput setaf 2 = green
#tput setaf 3 = yellow
#tput setaf 4 = dark blue
#tput setaf 5 = purple
#tput setaf 6 = cyan
#tput setaf 7 = gray
#tput setaf 8 = light blue
##################################################################################################################

tput setaf 3;
echo ""
echo "################################################################"
echo "Install Ibus-helakuru from source"
echo "################################################################"
echo ""
echo;tput sgr0

# Install  Dependencies
sudo apt install ibus ibus-m17n -y

# Install Icons
sudo install -Dm644 icons/si-helakuru-phonetic.png -t /usr/share/m17n/icons/
sudo install -Dm644 icons/si-helakuru-wijesekara.png -t /usr/share/m17n/icons/

#  Install Mim
sudo install -Dm644 mim/si-helakuru-phonetic.mim -t /usr/share/m17n/
sudo install -Dm644 mim/si-helakuru-wijesekara.mim -t /usr/share/m17n/

tput setaf 2;
echo ""
echo "################################################################"
echo "Ibus-helakuru Packages has been installed"
echo "################################################################"
echo ""
echo;tput sgr0

